#ifndef CHPEG_CHPEG_BYTECODE_H
#define CHPEG_CHPEG_BYTECODE_H

#ifndef CHPEG_AMALGAMATION
#include "chpeg/chpeg_api.h"
#include "chpeg/bytecode.h"
#include "chpeg/opcodes.h"
#endif

#define CHPEG_DEF_GRAMMAR 0
#define CHPEG_DEF_DEFINITION 1
#define CHPEG_DEF_CHOICE 2
#define CHPEG_DEF_SEQUENCE 3
#define CHPEG_DEF_ELEMENT 4
#define CHPEG_DEF_PREDICATE 5
#define CHPEG_DEF_REPEAT 6
#define CHPEG_DEF_PRIMARY 7
#define CHPEG_DEF_REFSCOPE 8
#define CHPEG_DEF_MARK 9
#define CHPEG_DEF_REFERENCE 10
#define CHPEG_DEF_TRIM 11
#define CHPEG_DEF_OPTIONS 12
#define CHPEG_DEF_IDENTIFIER 13
#define CHPEG_DEF_LITERAL 14
#define CHPEG_DEF_CHARCLASS 15
#define CHPEG_DEF_CHARRANGE 16
#define CHPEG_DEF_CHAR 17
#define CHPEG_DEF_ESCCHAR 18
#define CHPEG_DEF_OCTCHAR 19
#define CHPEG_DEF_PLAINCHAR 20
#define CHPEG_DEF_PREDOP 21
#define CHPEG_DEF_REPOP 22
#define CHPEG_DEF_DOT 23
#define CHPEG_DEF_S 24

CHPEG_API const ChpegByteCode chpeg_bytecode;

#endif // #ifndef CHPEG_CHPEG_BYTECODE_H
