// arrays.c: AUTO-GENERATED - DO NOT EDIT
#include "arrays.h"
// AUTOGENERATED - DO NOT EDIT
// type='const char *' name='StringArray' basename='string_array' cls='StringArray'
#include <stdlib.h>
#ifndef ARRAY_AMAL
#include "string_array.h"
#endif

ARRAY_DEF void StringArray_cleanup(StringArray *self)
{
    if (self->data) {
        free(self->data);
    }
    self->data = NULL;
    self->capacity = 0;
}

ARRAY_DEF void StringArray_clear(StringArray *self)
{
    self->size = 0;
}

ARRAY_DEF void StringArray_expand(StringArray *self, size_t length)
{
    while (length > self->capacity) {
        if (self->capacity == 0) {
            self->capacity = 1;
            self->data = (const char **)malloc(self->capacity * sizeof(const char *));
        }
        else {
            self->capacity *= 2;
            self->data = (const char **)realloc(self->data, self->capacity * sizeof(const char *));
        }
    }
}

ARRAY_DEF void StringArray_push_back(StringArray *self, const char * elem)
{
    StringArray_expand(self, self->size + 1);
    self->data[self->size++] = elem;
}
// AUTOGENERATED - DO NOT EDIT
// type='Grammar' name='GrammarArray' basename='grammar_array' cls='GrammarArray'
#include <stdlib.h>
#ifndef ARRAY_AMAL
#include "grammar_array.h"
#endif

ARRAY_DEF void GrammarArray_cleanup(GrammarArray *self)
{
    if (self->data) {
        free(self->data);
    }
    self->data = NULL;
    self->capacity = 0;
}

ARRAY_DEF void GrammarArray_clear(GrammarArray *self)
{
    self->size = 0;
}

ARRAY_DEF void GrammarArray_expand(GrammarArray *self, size_t length)
{
    while (length > self->capacity) {
        if (self->capacity == 0) {
            self->capacity = 1;
            self->data = (Grammar*)malloc(self->capacity * sizeof(Grammar));
        }
        else {
            self->capacity *= 2;
            self->data = (Grammar*)realloc(self->data, self->capacity * sizeof(Grammar));
        }
    }
}

ARRAY_DEF void GrammarArray_push_back(GrammarArray *self, Grammar elem)
{
    GrammarArray_expand(self, self->size + 1);
    self->data[self->size++] = elem;
}
// AUTOGENERATED - DO NOT EDIT
// type='Parse' name='ParseArray' basename='parse_array' cls='ParseArray'
#include <stdlib.h>
#ifndef ARRAY_AMAL
#include "parse_array.h"
#endif

ARRAY_DEF void ParseArray_cleanup(ParseArray *self)
{
    if (self->data) {
        free(self->data);
    }
    self->data = NULL;
    self->capacity = 0;
}

ARRAY_DEF void ParseArray_clear(ParseArray *self)
{
    self->size = 0;
}

ARRAY_DEF void ParseArray_expand(ParseArray *self, size_t length)
{
    while (length > self->capacity) {
        if (self->capacity == 0) {
            self->capacity = 1;
            self->data = (Parse*)malloc(self->capacity * sizeof(Parse));
        }
        else {
            self->capacity *= 2;
            self->data = (Parse*)realloc(self->data, self->capacity * sizeof(Parse));
        }
    }
}

ARRAY_DEF void ParseArray_push_back(ParseArray *self, Parse elem)
{
    ParseArray_expand(self, self->size + 1);
    self->data[self->size++] = elem;
}
