// arrays.h: AUTO-GENERATED - DO NOT EDIT
#define ARRAY_AMAL
#define ARRAY_API extern
#define ARRAY_DEF
#include "app.h"
// AUTOGENERATED - DO NOT EDIT
// type='const char *' name='StringArray' basename='string_array' cls='StringArray'
#ifndef STRING_ARRAY_H
#define STRING_ARRAY_H

#include <stdlib.h>


typedef struct _StringArray {
    size_t size;
    size_t capacity;
    const char * *data;
} StringArray;

ARRAY_API void StringArray_clear(StringArray *self);
ARRAY_API void StringArray_cleanup(StringArray *self);
ARRAY_API void StringArray_expand(StringArray *self, size_t length);
ARRAY_API void StringArray_push_back(StringArray *self, const char * elem);

#endif // #ifndef STRING_ARRAY_H
// AUTOGENERATED - DO NOT EDIT
// type='Grammar' name='GrammarArray' basename='grammar_array' cls='GrammarArray'
#ifndef GRAMMAR_ARRAY_H
#define GRAMMAR_ARRAY_H

#include <stdlib.h>
#include "grammar.h"

typedef struct _GrammarArray {
    size_t size;
    size_t capacity;
    Grammar *data;
} GrammarArray;

ARRAY_API void GrammarArray_clear(GrammarArray *self);
ARRAY_API void GrammarArray_cleanup(GrammarArray *self);
ARRAY_API void GrammarArray_expand(GrammarArray *self, size_t length);
ARRAY_API void GrammarArray_push_back(GrammarArray *self, Grammar elem);

#endif // #ifndef GRAMMAR_ARRAY_H
// AUTOGENERATED - DO NOT EDIT
// type='Parse' name='ParseArray' basename='parse_array' cls='ParseArray'
#ifndef PARSE_ARRAY_H
#define PARSE_ARRAY_H

#include <stdlib.h>
#include "parse.h"

typedef struct _ParseArray {
    size_t size;
    size_t capacity;
    Parse *data;
} ParseArray;

ARRAY_API void ParseArray_clear(ParseArray *self);
ARRAY_API void ParseArray_cleanup(ParseArray *self);
ARRAY_API void ParseArray_expand(ParseArray *self, size_t length);
ARRAY_API void ParseArray_push_back(ParseArray *self, Parse elem);

#endif // #ifndef PARSE_ARRAY_H
