# src: https://github-wiki-see.page/m/PhilippeSigaud/Pegged/wiki/Left-Recursion#
#
#Interlocking cycles
#It can yet be more complicated. For inputs like nlm-n+(aaa)n, this grammar has several interlocking left-recursive cycles:

        S <- E eoi
        E <- F 'n' / 'n'
        F <- E '+' I* / G '-'
        G <- H 'm' / E
        H <- G 'l'
        I <- '(' A+ ')'
        A <- 'a'

# additional defs needed

eoi <- !.
