#include "chpeg_bytecode.h"

// this version of the hardcoded byte code started with the version output by the Ruby bootstrap process

const ChpegByteCode chpeg_bytecode = {
    .num_defs = 20,

    .def_names = (char*[20]) {"Grammar", "Definition", "Choice", "Sequence", "Predicate", "Repeat", "Primary", "Options", "Identifier", "Literal", "CharClass", "CharRange", "Char", "EscChar", "OctChar", "PlainChar", "PredOp", "RepOp", "Dot", "S"},

    .def_flags = (int[20]) {CHPEG_STOP, 0, 0, 0, 0, 0, 0, 0, CHPEG_LEAF, CHPEG_STOP, CHPEG_STOP, 0, 0, CHPEG_LEAF, CHPEG_LEAF, CHPEG_LEAF, CHPEG_LEAF, CHPEG_LEAF, CHPEG_LEAF, CHPEG_IGNORE},

    .def_addrs = (int[20]) {2, 15, 42, 55, 62, 73, 84, 129, 136, 145, 181, 197, 218, 234, 240, 265, 273, 277, 281, 285}, // presubtracted by 1

    .num_instructions = 315,

    .instructions = (int[315]) {
    /*     0 <:Grammar 0 (Grammar) []>                */ CHPEG_INST(CHPEG_OP_IDENT, 0),
    /*     1 <:Grammar 0 (Grammar) []>                */ CHPEG_INST(CHPEG_OP_FAIL, 0),
    /*     2 <:Grammar 0 (Grammar) []>                */ CHPEG_INST(CHPEG_OP_SUCC, 0),
    /*     3 <---:Identifier 4 (Grammar[0]) "S">      */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*     4 <---:Identifier 4 (Grammar[0]) "S">      */ CHPEG_INST(CHPEG_OP_GOTO, 14),
    /*     5 <---:Repeat 5 (Grammar[1]) []>           */ CHPEG_INST(CHPEG_OP_RPBEG, 0),
    /*     6 <----:Identifier 6 (Grammar[1][0]) "Definition"> */ CHPEG_INST(CHPEG_OP_IDENT, 1),
    /*     7 <----:Identifier 6 (Grammar[1][0]) "Definition"> */ CHPEG_INST(CHPEG_OP_GOTO, 8),
    /*     8 <---:Repeat 5 (Grammar[1]) []>           */ CHPEG_INST(CHPEG_OP_RPMAT, 5),
    /*     9 <---:Repeat 5 (Grammar[1]) []>           */ CHPEG_INST(CHPEG_OP_RPDONE, 14),
    /*    10 <---:Predicate 7 (Grammar[2]) []>        */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*    11 <----:Dot 8 (Grammar[2][0]) ".">         */ CHPEG_INST(CHPEG_OP_DOT, 12),
    /*    12 <---:Predicate 7 (Grammar[2]) []>        */ CHPEG_INST(CHPEG_OP_PMATCHF, 14),
    /*    13 <---:Predicate 7 (Grammar[2]) []>        */ CHPEG_INST(CHPEG_OP_PNOMATS, 14),
    /*    14 <-:Definition 1 (def:Grammar) []> {S}    */ CHPEG_INST(CHPEG_OP_ISUCC, 0),
    /*    15 <-:Definition 1 (def:Grammar) []> {S}    */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*    16 <---:Identifier 12 (Definition[0]) "Identifier"> */ CHPEG_INST(CHPEG_OP_IDENT, 8),
    /*    17 <---:Identifier 12 (Definition[0]) "Identifier"> */ CHPEG_INST(CHPEG_OP_GOTO, 41),
    /*    18 <---:Identifier 13 (Definition[1]) "S">  */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    19 <---:Identifier 13 (Definition[1]) "S">  */ CHPEG_INST(CHPEG_OP_GOTO, 41),
    /*    20 <---:Repeat 14 (Definition[2]) []>       */ CHPEG_INST(CHPEG_OP_RQBEG, 0),
    /*    21 <-----:Literal  (Definition[2][0][0]) "{"> */ CHPEG_INST(CHPEG_OP_LIT, 0),
    /*    22 <-----:Literal  (Definition[2][0][0]) "{"> */ CHPEG_INST(CHPEG_OP_GOTO, 33),
    /*    23 <-----:Identifier 16 (Definition[2][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    24 <-----:Identifier 16 (Definition[2][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 33),
    /*    25 <-----:Identifier 17 (Definition[2][0][2]) "Options"> */ CHPEG_INST(CHPEG_OP_IDENT, 7),
    /*    26 <-----:Identifier 17 (Definition[2][0][2]) "Options"> */ CHPEG_INST(CHPEG_OP_GOTO, 33),
    /*    27 <-----:Identifier 18 (Definition[2][0][3]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    28 <-----:Identifier 18 (Definition[2][0][3]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 33),
    /*    29 <-----:Literal  (Definition[2][0][4]) "}"> */ CHPEG_INST(CHPEG_OP_LIT, 1),
    /*    30 <-----:Literal  (Definition[2][0][4]) "}"> */ CHPEG_INST(CHPEG_OP_GOTO, 33),
    /*    31 <-----:Identifier 19 (Definition[2][0][5]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    32 <-----:Identifier 19 (Definition[2][0][5]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 33),
    /*    33 <---:Repeat 14 (Definition[2]) []>       */ CHPEG_INST(CHPEG_OP_RQMAT, 0),
    /*    34 <---:Repeat 14 (Definition[2]) []>       */ CHPEG_INST(CHPEG_OP_RQDONE, 0),
    /*    35 <---:Literal  (Definition[3]) "<-">      */ CHPEG_INST(CHPEG_OP_LIT, 2),
    /*    36 <---:Literal  (Definition[3]) "<-">      */ CHPEG_INST(CHPEG_OP_GOTO, 41),
    /*    37 <---:Identifier 20 (Definition[4]) "S">  */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    38 <---:Identifier 20 (Definition[4]) "S">  */ CHPEG_INST(CHPEG_OP_GOTO, 41),
    /*    39 <---:Identifier 21 (Definition[5]) "Choice"> */ CHPEG_INST(CHPEG_OP_IDENT, 2),
    /*    40 <---:Identifier 21 (Definition[5]) "Choice"> */ CHPEG_INST(CHPEG_OP_GOTO, 41),
    /*    41 <-:Definition 9 (def:Definition) []> {}  */ CHPEG_INST(CHPEG_OP_ISUCC, 1),
    /*    42 <-:Definition 9 (def:Definition) []> {}  */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*    43 <---:Identifier 25 (Choice[0]) "Sequence"> */ CHPEG_INST(CHPEG_OP_IDENT, 3),
    /*    44 <---:Identifier 25 (Choice[0]) "Sequence"> */ CHPEG_INST(CHPEG_OP_GOTO, 54),
    /*    45 <---:Repeat 26 (Choice[1]) []>           */ CHPEG_INST(CHPEG_OP_RSBEG, 0),
    /*    46 <-----:Literal  (Choice[1][0][0]) "/">   */ CHPEG_INST(CHPEG_OP_LIT, 3),
    /*    47 <-----:Literal  (Choice[1][0][0]) "/">   */ CHPEG_INST(CHPEG_OP_GOTO, 52),
    /*    48 <-----:Identifier 28 (Choice[1][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    49 <-----:Identifier 28 (Choice[1][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 52),
    /*    50 <-----:Identifier 29 (Choice[1][0][2]) "Sequence"> */ CHPEG_INST(CHPEG_OP_IDENT, 3),
    /*    51 <-----:Identifier 29 (Choice[1][0][2]) "Sequence"> */ CHPEG_INST(CHPEG_OP_GOTO, 52),
    /*    52 <---:Repeat 26 (Choice[1]) []>           */ CHPEG_INST(CHPEG_OP_RSMAT, 45),
    /*    53 <---:Repeat 26 (Choice[1]) []>           */ CHPEG_INST(CHPEG_OP_RSDONE, 0),
    /*    54 <-:Definition 22 (def:Choice) []> {}     */ CHPEG_INST(CHPEG_OP_ISUCC, 2),
    /*    55 <-:Definition 22 (def:Choice) []> {}     */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*    56 <--:Repeat 32 (Sequence) []>             */ CHPEG_INST(CHPEG_OP_RPBEG, 0),
    /*    57 <---:Identifier 33 (Sequence[0]) "Predicate"> */ CHPEG_INST(CHPEG_OP_IDENT, 4),
    /*    58 <---:Identifier 33 (Sequence[0]) "Predicate"> */ CHPEG_INST(CHPEG_OP_GOTO, 59),
    /*    59 <--:Repeat 32 (Sequence) []>             */ CHPEG_INST(CHPEG_OP_RPMAT, 56),
    /*    60 <--:Repeat 32 (Sequence) []>             */ CHPEG_INST(CHPEG_OP_RPDONE, 61),
    /*    61 <-:Definition 30 (def:Sequence) []> {}   */ CHPEG_INST(CHPEG_OP_ISUCC, 3),
    /*    62 <-:Definition 30 (def:Sequence) []> {}   */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*    63 <---:Repeat 37 (Predicate[0]) []>        */ CHPEG_INST(CHPEG_OP_RQBEG, 0),
    /*    64 <-----:Identifier 39 (Predicate[0][0][0]) "PredOp"> */ CHPEG_INST(CHPEG_OP_IDENT, 16),
    /*    65 <-----:Identifier 39 (Predicate[0][0][0]) "PredOp"> */ CHPEG_INST(CHPEG_OP_GOTO, 68),
    /*    66 <-----:Identifier 40 (Predicate[0][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    67 <-----:Identifier 40 (Predicate[0][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 68),
    /*    68 <---:Repeat 37 (Predicate[0]) []>        */ CHPEG_INST(CHPEG_OP_RQMAT, 0),
    /*    69 <---:Repeat 37 (Predicate[0]) []>        */ CHPEG_INST(CHPEG_OP_RQDONE, 0),
    /*    70 <---:Identifier 41 (Predicate[1]) "Repeat"> */ CHPEG_INST(CHPEG_OP_IDENT, 5),
    /*    71 <---:Identifier 41 (Predicate[1]) "Repeat"> */ CHPEG_INST(CHPEG_OP_GOTO, 72),
    /*    72 <-:Definition 34 (def:Predicate) []> {}  */ CHPEG_INST(CHPEG_OP_ISUCC, 4),
    /*    73 <-:Definition 34 (def:Predicate) []> {}  */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*    74 <---:Identifier 45 (Repeat[0]) "Primary"> */ CHPEG_INST(CHPEG_OP_IDENT, 6),
    /*    75 <---:Identifier 45 (Repeat[0]) "Primary"> */ CHPEG_INST(CHPEG_OP_GOTO, 83),
    /*    76 <---:Repeat 46 (Repeat[1]) []>           */ CHPEG_INST(CHPEG_OP_RQBEG, 0),
    /*    77 <-----:Identifier 48 (Repeat[1][0][0]) "RepOp"> */ CHPEG_INST(CHPEG_OP_IDENT, 17),
    /*    78 <-----:Identifier 48 (Repeat[1][0][0]) "RepOp"> */ CHPEG_INST(CHPEG_OP_GOTO, 81),
    /*    79 <-----:Identifier 49 (Repeat[1][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    80 <-----:Identifier 49 (Repeat[1][0][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 81),
    /*    81 <---:Repeat 46 (Repeat[1]) []>           */ CHPEG_INST(CHPEG_OP_RQMAT, 0),
    /*    82 <---:Repeat 46 (Repeat[1]) []>           */ CHPEG_INST(CHPEG_OP_RQDONE, 0),
    /*    83 <-:Definition 42 (def:Repeat) []> {}     */ CHPEG_INST(CHPEG_OP_ISUCC, 5),
    /*    84 <-:Definition 42 (def:Repeat) []> {}     */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*    85 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CHOICE, 0),
    /*    86 <----:Identifier 54 (Primary[0][0]) "Identifier"> */ CHPEG_INST(CHPEG_OP_IDENT, 8),
    /*    87 <----:Identifier 54 (Primary[0][0]) "Identifier"> */ CHPEG_INST(CHPEG_OP_GOTO, 95),
    /*    88 <----:Identifier 55 (Primary[0][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*    89 <----:Identifier 55 (Primary[0][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 95),
    /*    90 <----:Predicate 56 (Primary[0][2]) []>   */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*    91 <-----:CharClass  (Primary[0][2][0]) []> */ CHPEG_INST(CHPEG_OP_CHRCLS, 4),
    /*    92 <-----:CharClass  (Primary[0][2][0]) []> */ CHPEG_INST(CHPEG_OP_GOTO, 93),
    /*    93 <----:Predicate 56 (Primary[0][2]) []>   */ CHPEG_INST(CHPEG_OP_PMATCHF, 95),
    /*    94 <----:Predicate 56 (Primary[0][2]) []>   */ CHPEG_INST(CHPEG_OP_PNOMATS, 95),
    /*    95 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CISUCC, 127),
    /*    96 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*    97 <----:Literal  (Primary[1][0]) "(">      */ CHPEG_INST(CHPEG_OP_LIT, 5),
    /*    98 <----:Literal  (Primary[1][0]) "(">      */ CHPEG_INST(CHPEG_OP_GOTO, 107),
    /*    99 <----:Identifier 58 (Primary[1][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*   100 <----:Identifier 58 (Primary[1][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 107),
    /*   101 <----:Identifier 59 (Primary[1][2]) "Choice"> */ CHPEG_INST(CHPEG_OP_IDENT, 2),
    /*   102 <----:Identifier 59 (Primary[1][2]) "Choice"> */ CHPEG_INST(CHPEG_OP_GOTO, 107),
    /*   103 <----:Literal  (Primary[1][3]) ")">      */ CHPEG_INST(CHPEG_OP_LIT, 6),
    /*   104 <----:Literal  (Primary[1][3]) ")">      */ CHPEG_INST(CHPEG_OP_GOTO, 107),
    /*   105 <----:Identifier 60 (Primary[1][4]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*   106 <----:Identifier 60 (Primary[1][4]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 107),
    /*   107 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CISUCC, 127),
    /*   108 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   109 <----:Identifier 62 (Primary[2][0]) "Literal"> */ CHPEG_INST(CHPEG_OP_IDENT, 9),
    /*   110 <----:Identifier 62 (Primary[2][0]) "Literal"> */ CHPEG_INST(CHPEG_OP_GOTO, 113),
    /*   111 <----:Identifier 63 (Primary[2][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*   112 <----:Identifier 63 (Primary[2][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 113),
    /*   113 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CISUCC, 127),
    /*   114 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   115 <----:Identifier 65 (Primary[3][0]) "CharClass"> */ CHPEG_INST(CHPEG_OP_IDENT, 10),
    /*   116 <----:Identifier 65 (Primary[3][0]) "CharClass"> */ CHPEG_INST(CHPEG_OP_GOTO, 119),
    /*   117 <----:Identifier 66 (Primary[3][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*   118 <----:Identifier 66 (Primary[3][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 119),
    /*   119 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CISUCC, 127),
    /*   120 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   121 <----:Identifier 68 (Primary[4][0]) "Dot"> */ CHPEG_INST(CHPEG_OP_IDENT, 18),
    /*   122 <----:Identifier 68 (Primary[4][0]) "Dot"> */ CHPEG_INST(CHPEG_OP_GOTO, 125),
    /*   123 <----:Identifier 69 (Primary[4][1]) "S"> */ CHPEG_INST(CHPEG_OP_IDENT, 19),
    /*   124 <----:Identifier 69 (Primary[4][1]) "S"> */ CHPEG_INST(CHPEG_OP_GOTO, 125),
    /*   125 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CISUCC, 127),
    /*   126 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   127 <--:Choice 52 (Primary) []>              */ CHPEG_INST(CHPEG_OP_CFAIL, 128),
    /*   128 <-:Definition 50 (def:Primary) []> {}    */ CHPEG_INST(CHPEG_OP_ISUCC, 6),
    /*   129 <-:Definition 50 (def:Primary) []> {}    */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   130 <--:Repeat 72 (Options) []>              */ CHPEG_INST(CHPEG_OP_RSBEG, 0),
    /*   131 <---:CharClass  (Options[0]) []>         */ CHPEG_INST(CHPEG_OP_CHRCLS, 7),
    /*   132 <---:CharClass  (Options[0]) []>         */ CHPEG_INST(CHPEG_OP_GOTO, 133),
    /*   133 <--:Repeat 72 (Options) []>              */ CHPEG_INST(CHPEG_OP_RSMAT, 130),
    /*   134 <--:Repeat 72 (Options) []>              */ CHPEG_INST(CHPEG_OP_RSDONE, 0),
    /*   135 <-:Definition 70 (def:Options) []> {}    */ CHPEG_INST(CHPEG_OP_ISUCC, 7),
    /*   136 <-:Definition 70 (def:Options) []> {}    */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   137 <---:CharClass  (Identifier[0]) []>      */ CHPEG_INST(CHPEG_OP_CHRCLS, 8),
    /*   138 <---:CharClass  (Identifier[0]) []>      */ CHPEG_INST(CHPEG_OP_GOTO, 144),
    /*   139 <---:Repeat 76 (Identifier[1]) []>       */ CHPEG_INST(CHPEG_OP_RSBEG, 0),
    /*   140 <----:CharClass  (Identifier[1][0]) []>  */ CHPEG_INST(CHPEG_OP_CHRCLS, 9),
    /*   141 <----:CharClass  (Identifier[1][0]) []>  */ CHPEG_INST(CHPEG_OP_GOTO, 142),
    /*   142 <---:Repeat 76 (Identifier[1]) []>       */ CHPEG_INST(CHPEG_OP_RSMAT, 139),
    /*   143 <---:Repeat 76 (Identifier[1]) []>       */ CHPEG_INST(CHPEG_OP_RSDONE, 0),
    /*   144 <-:Definition 73 (def:Identifier) []> {L} */ CHPEG_INST(CHPEG_OP_ISUCC, 8),
    /*   145 <-:Definition 73 (def:Identifier) []> {L} */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   146 <--:Choice 79 (Literal) []>              */ CHPEG_INST(CHPEG_OP_CHOICE, 0),
    /*   147 <----:CharClass  (Literal[0][0]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 10),
    /*   148 <----:CharClass  (Literal[0][0]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 161),
    /*   149 <----:Repeat 81 (Literal[0][1]) []>      */ CHPEG_INST(CHPEG_OP_RSBEG, 0),
    /*   150 <------:Predicate 83 (Literal[0][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*   151 <-------:CharClass  (Literal[0][1][0][0][0]) []> */ CHPEG_INST(CHPEG_OP_CHRCLS, 10),
    /*   152 <-------:CharClass  (Literal[0][1][0][0][0]) []> */ CHPEG_INST(CHPEG_OP_GOTO, 153),
    /*   153 <------:Predicate 83 (Literal[0][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PMATCHF, 157),
    /*   154 <------:Predicate 83 (Literal[0][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PNOMATS, 157),
    /*   155 <------:Identifier 84 (Literal[0][1][0][1]) "Char"> */ CHPEG_INST(CHPEG_OP_IDENT, 12),
    /*   156 <------:Identifier 84 (Literal[0][1][0][1]) "Char"> */ CHPEG_INST(CHPEG_OP_GOTO, 157),
    /*   157 <----:Repeat 81 (Literal[0][1]) []>      */ CHPEG_INST(CHPEG_OP_RSMAT, 149),
    /*   158 <----:Repeat 81 (Literal[0][1]) []>      */ CHPEG_INST(CHPEG_OP_RSDONE, 0),
    /*   159 <----:CharClass  (Literal[0][2]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 10),
    /*   160 <----:CharClass  (Literal[0][2]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 161),
    /*   161 <--:Choice 79 (Literal) []>              */ CHPEG_INST(CHPEG_OP_CISUCC, 179),
    /*   162 <--:Choice 79 (Literal) []>              */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   163 <----:CharClass  (Literal[1][0]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 11),
    /*   164 <----:CharClass  (Literal[1][0]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 177),
    /*   165 <----:Repeat 86 (Literal[1][1]) []>      */ CHPEG_INST(CHPEG_OP_RSBEG, 0),
    /*   166 <------:Predicate 88 (Literal[1][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*   167 <-------:CharClass  (Literal[1][1][0][0][0]) []> */ CHPEG_INST(CHPEG_OP_CHRCLS, 11),
    /*   168 <-------:CharClass  (Literal[1][1][0][0][0]) []> */ CHPEG_INST(CHPEG_OP_GOTO, 169),
    /*   169 <------:Predicate 88 (Literal[1][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PMATCHF, 173),
    /*   170 <------:Predicate 88 (Literal[1][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PNOMATS, 173),
    /*   171 <------:Identifier 89 (Literal[1][1][0][1]) "Char"> */ CHPEG_INST(CHPEG_OP_IDENT, 12),
    /*   172 <------:Identifier 89 (Literal[1][1][0][1]) "Char"> */ CHPEG_INST(CHPEG_OP_GOTO, 173),
    /*   173 <----:Repeat 86 (Literal[1][1]) []>      */ CHPEG_INST(CHPEG_OP_RSMAT, 165),
    /*   174 <----:Repeat 86 (Literal[1][1]) []>      */ CHPEG_INST(CHPEG_OP_RSDONE, 0),
    /*   175 <----:CharClass  (Literal[1][2]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 11),
    /*   176 <----:CharClass  (Literal[1][2]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 177),
    /*   177 <--:Choice 79 (Literal) []>              */ CHPEG_INST(CHPEG_OP_CISUCC, 179),
    /*   178 <--:Choice 79 (Literal) []>              */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   179 <--:Choice 79 (Literal) []>              */ CHPEG_INST(CHPEG_OP_CFAIL, 180),
    /*   180 <-:Definition 77 (def:Literal) []> {S}   */ CHPEG_INST(CHPEG_OP_ISUCC, 9),
    /*   181 <-:Definition 77 (def:Literal) []> {S}   */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   182 <---:Literal  (CharClass[0]) "[">        */ CHPEG_INST(CHPEG_OP_LIT, 12),
    /*   183 <---:Literal  (CharClass[0]) "[">        */ CHPEG_INST(CHPEG_OP_GOTO, 196),
    /*   184 <---:Repeat 93 (CharClass[1]) []>        */ CHPEG_INST(CHPEG_OP_RPBEG, 0),
    /*   185 <-----:Predicate 95 (CharClass[1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*   186 <------:Literal  (CharClass[1][0][0][0]) "]"> */ CHPEG_INST(CHPEG_OP_LIT, 13),
    /*   187 <------:Literal  (CharClass[1][0][0][0]) "]"> */ CHPEG_INST(CHPEG_OP_GOTO, 188),
    /*   188 <-----:Predicate 95 (CharClass[1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PMATCHF, 192),
    /*   189 <-----:Predicate 95 (CharClass[1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PNOMATS, 192),
    /*   190 <-----:Identifier 96 (CharClass[1][0][1]) "CharRange"> */ CHPEG_INST(CHPEG_OP_IDENT, 11),
    /*   191 <-----:Identifier 96 (CharClass[1][0][1]) "CharRange"> */ CHPEG_INST(CHPEG_OP_GOTO, 192),
    /*   192 <---:Repeat 93 (CharClass[1]) []>        */ CHPEG_INST(CHPEG_OP_RPMAT, 184),
    /*   193 <---:Repeat 93 (CharClass[1]) []>        */ CHPEG_INST(CHPEG_OP_RPDONE, 196),
    /*   194 <---:Literal  (CharClass[2]) "]">        */ CHPEG_INST(CHPEG_OP_LIT, 13),
    /*   195 <---:Literal  (CharClass[2]) "]">        */ CHPEG_INST(CHPEG_OP_GOTO, 196),
    /*   196 <-:Definition 90 (def:CharClass) []> {S} */ CHPEG_INST(CHPEG_OP_ISUCC, 10),
    /*   197 <-:Definition 90 (def:CharClass) []> {S} */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   198 <--:Choice 99 (CharRange) []>            */ CHPEG_INST(CHPEG_OP_CHOICE, 0),
    /*   199 <----:Identifier 101 (CharRange[0][0]) "Char"> */ CHPEG_INST(CHPEG_OP_IDENT, 12),
    /*   200 <----:Identifier 101 (CharRange[0][0]) "Char"> */ CHPEG_INST(CHPEG_OP_GOTO, 210),
    /*   201 <----:Literal  (CharRange[0][1]) "-">    */ CHPEG_INST(CHPEG_OP_LIT, 14),
    /*   202 <----:Literal  (CharRange[0][1]) "-">    */ CHPEG_INST(CHPEG_OP_GOTO, 210),
    /*   203 <----:Predicate 102 (CharRange[0][2]) []> */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*   204 <-----:Literal  (CharRange[0][2][0]) "]"> */ CHPEG_INST(CHPEG_OP_LIT, 13),
    /*   205 <-----:Literal  (CharRange[0][2][0]) "]"> */ CHPEG_INST(CHPEG_OP_GOTO, 206),
    /*   206 <----:Predicate 102 (CharRange[0][2]) []> */ CHPEG_INST(CHPEG_OP_PMATCHF, 210),
    /*   207 <----:Predicate 102 (CharRange[0][2]) []> */ CHPEG_INST(CHPEG_OP_PNOMATS, 210),
    /*   208 <----:Identifier 103 (CharRange[0][3]) "Char"> */ CHPEG_INST(CHPEG_OP_IDENT, 12),
    /*   209 <----:Identifier 103 (CharRange[0][3]) "Char"> */ CHPEG_INST(CHPEG_OP_GOTO, 210),
    /*   210 <--:Choice 99 (CharRange) []>            */ CHPEG_INST(CHPEG_OP_CISUCC, 216),
    /*   211 <--:Choice 99 (CharRange) []>            */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   212 <---:Identifier 104 (CharRange[1]) "Char"> {E} */ CHPEG_INST(CHPEG_OP_IDENT, 12),
    /*   213 <---:Identifier 104 (CharRange[1]) "Char"> {E} */ CHPEG_INST(CHPEG_OP_GOTO, 214),
    /*   214 <--:Choice 99 (CharRange) []>            */ CHPEG_INST(CHPEG_OP_CISUCC, 216),
    /*   215 <--:Choice 99 (CharRange) []>            */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   216 <--:Choice 99 (CharRange) []>            */ CHPEG_INST(CHPEG_OP_CFAIL, 217),
    /*   217 <-:Definition 97 (def:CharRange) []> {}  */ CHPEG_INST(CHPEG_OP_ISUCC, 11),
    /*   218 <-:Definition 97 (def:CharRange) []> {}  */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   219 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CHOICE, 0),
    /*   220 <---:Identifier 108 (Char[0]) "EscChar"> {E} */ CHPEG_INST(CHPEG_OP_IDENT, 13),
    /*   221 <---:Identifier 108 (Char[0]) "EscChar"> {E} */ CHPEG_INST(CHPEG_OP_GOTO, 222),
    /*   222 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CISUCC, 232),
    /*   223 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   224 <---:Identifier 109 (Char[1]) "OctChar"> {E} */ CHPEG_INST(CHPEG_OP_IDENT, 14),
    /*   225 <---:Identifier 109 (Char[1]) "OctChar"> {E} */ CHPEG_INST(CHPEG_OP_GOTO, 226),
    /*   226 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CISUCC, 232),
    /*   227 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   228 <---:Identifier 110 (Char[2]) "PlainChar"> {E} */ CHPEG_INST(CHPEG_OP_IDENT, 15),
    /*   229 <---:Identifier 110 (Char[2]) "PlainChar"> {E} */ CHPEG_INST(CHPEG_OP_GOTO, 230),
    /*   230 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CISUCC, 232),
    /*   231 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   232 <--:Choice 107 (Char) []>                */ CHPEG_INST(CHPEG_OP_CFAIL, 233),
    /*   233 <-:Definition 105 (def:Char) []> {}      */ CHPEG_INST(CHPEG_OP_ISUCC, 12),
    /*   234 <-:Definition 105 (def:Char) []> {}      */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   235 <---:Literal  (EscChar[0]) "\\">         */ CHPEG_INST(CHPEG_OP_LIT, 15),
    /*   236 <---:Literal  (EscChar[0]) "\\">         */ CHPEG_INST(CHPEG_OP_GOTO, 239),
    /*   237 <---:CharClass  (EscChar[1]) []>         */ CHPEG_INST(CHPEG_OP_CHRCLS, 16),
    /*   238 <---:CharClass  (EscChar[1]) []>         */ CHPEG_INST(CHPEG_OP_GOTO, 239),
    /*   239 <-:Definition 111 (def:EscChar) []> {L}  */ CHPEG_INST(CHPEG_OP_ISUCC, 13),
    /*   240 <-:Definition 111 (def:EscChar) []> {L}  */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   241 <--:Choice 116 (OctChar) []>             */ CHPEG_INST(CHPEG_OP_CHOICE, 0),
    /*   242 <----:Literal  (OctChar[0][0]) "\\">     */ CHPEG_INST(CHPEG_OP_LIT, 15),
    /*   243 <----:Literal  (OctChar[0][0]) "\\">     */ CHPEG_INST(CHPEG_OP_GOTO, 250),
    /*   244 <----:CharClass  (OctChar[0][1]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 17),
    /*   245 <----:CharClass  (OctChar[0][1]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 250),
    /*   246 <----:CharClass  (OctChar[0][2]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 18),
    /*   247 <----:CharClass  (OctChar[0][2]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 250),
    /*   248 <----:CharClass  (OctChar[0][3]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 18),
    /*   249 <----:CharClass  (OctChar[0][3]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 250),
    /*   250 <--:Choice 116 (OctChar) []>             */ CHPEG_INST(CHPEG_OP_CISUCC, 263),
    /*   251 <--:Choice 116 (OctChar) []>             */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   252 <----:Literal  (OctChar[1][0]) "\\">     */ CHPEG_INST(CHPEG_OP_LIT, 15),
    /*   253 <----:Literal  (OctChar[1][0]) "\\">     */ CHPEG_INST(CHPEG_OP_GOTO, 261),
    /*   254 <----:CharClass  (OctChar[1][1]) []>     */ CHPEG_INST(CHPEG_OP_CHRCLS, 18),
    /*   255 <----:CharClass  (OctChar[1][1]) []>     */ CHPEG_INST(CHPEG_OP_GOTO, 261),
    /*   256 <----:Repeat 119 (OctChar[1][2]) []>     */ CHPEG_INST(CHPEG_OP_RQBEG, 0),
    /*   257 <-----:CharClass  (OctChar[1][2][0]) []> */ CHPEG_INST(CHPEG_OP_CHRCLS, 18),
    /*   258 <-----:CharClass  (OctChar[1][2][0]) []> */ CHPEG_INST(CHPEG_OP_GOTO, 259),
    /*   259 <----:Repeat 119 (OctChar[1][2]) []>     */ CHPEG_INST(CHPEG_OP_RQMAT, 0),
    /*   260 <----:Repeat 119 (OctChar[1][2]) []>     */ CHPEG_INST(CHPEG_OP_RQDONE, 0),
    /*   261 <--:Choice 116 (OctChar) []>             */ CHPEG_INST(CHPEG_OP_CISUCC, 263),
    /*   262 <--:Choice 116 (OctChar) []>             */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   263 <--:Choice 116 (OctChar) []>             */ CHPEG_INST(CHPEG_OP_CFAIL, 264),
    /*   264 <-:Definition 114 (def:OctChar) []> {L}  */ CHPEG_INST(CHPEG_OP_ISUCC, 14),
    /*   265 <-:Definition 114 (def:OctChar) []> {L}  */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   266 <---:Predicate 123 (PlainChar[0]) []>    */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*   267 <----:Literal  (PlainChar[0][0]) "\\">   */ CHPEG_INST(CHPEG_OP_LIT, 15),
    /*   268 <----:Literal  (PlainChar[0][0]) "\\">   */ CHPEG_INST(CHPEG_OP_GOTO, 269),
    /*   269 <---:Predicate 123 (PlainChar[0]) []>    */ CHPEG_INST(CHPEG_OP_PMATCHF, 272),
    /*   270 <---:Predicate 123 (PlainChar[0]) []>    */ CHPEG_INST(CHPEG_OP_PNOMATS, 272),
    /*   271 <---:Dot 124 (PlainChar[1]) ".">         */ CHPEG_INST(CHPEG_OP_DOT, 272),
    /*   272 <-:Definition 120 (def:PlainChar) []> {L} */ CHPEG_INST(CHPEG_OP_ISUCC, 15),
    /*   273 <-:Definition 120 (def:PlainChar) []> {L} */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   274 <--:CharClass  (PredOp) []>              */ CHPEG_INST(CHPEG_OP_CHRCLS, 19),
    /*   275 <--:CharClass  (PredOp) []>              */ CHPEG_INST(CHPEG_OP_GOTO, 276),
    /*   276 <-:Definition 125 (def:PredOp) []> {L}   */ CHPEG_INST(CHPEG_OP_ISUCC, 16),
    /*   277 <-:Definition 125 (def:PredOp) []> {L}   */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   278 <--:CharClass  (RepOp) []>               */ CHPEG_INST(CHPEG_OP_CHRCLS, 20),
    /*   279 <--:CharClass  (RepOp) []>               */ CHPEG_INST(CHPEG_OP_GOTO, 280),
    /*   280 <-:Definition 127 (def:RepOp) []> {L}    */ CHPEG_INST(CHPEG_OP_ISUCC, 17),
    /*   281 <-:Definition 127 (def:RepOp) []> {L}    */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   282 <--:Literal  (Dot) ".">                  */ CHPEG_INST(CHPEG_OP_LIT, 21),
    /*   283 <--:Literal  (Dot) ".">                  */ CHPEG_INST(CHPEG_OP_GOTO, 284),
    /*   284 <-:Definition 129 (def:Dot) []> {L}      */ CHPEG_INST(CHPEG_OP_ISUCC, 18),
    /*   285 <-:Definition 129 (def:Dot) []> {L}      */ CHPEG_INST(CHPEG_OP_IFAIL, 0),
    /*   286 <--:Repeat 133 (S) []>                   */ CHPEG_INST(CHPEG_OP_RSBEG, 0),
    /*   287 <---:Choice 134 (S[0]) []>               */ CHPEG_INST(CHPEG_OP_CHOICE, 0),
    /*   288 <----:Repeat 135 (S[0][0]) []> {E}       */ CHPEG_INST(CHPEG_OP_RPBEG, 0),
    /*   289 <-----:CharClass  (S[0][0][0]) []>       */ CHPEG_INST(CHPEG_OP_CHRCLS, 22),
    /*   290 <-----:CharClass  (S[0][0][0]) []>       */ CHPEG_INST(CHPEG_OP_GOTO, 291),
    /*   291 <----:Repeat 135 (S[0][0]) []> {E}       */ CHPEG_INST(CHPEG_OP_RPMAT, 288),
    /*   292 <----:Repeat 135 (S[0][0]) []> {E}       */ CHPEG_INST(CHPEG_OP_RPDONE, 293),
    /*   293 <---:Choice 134 (S[0]) []>               */ CHPEG_INST(CHPEG_OP_CISUCC, 310),
    /*   294 <---:Choice 134 (S[0]) []>               */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   295 <-----:Literal  (S[0][1][0]) "#">        */ CHPEG_INST(CHPEG_OP_LIT, 23),
    /*   296 <-----:Literal  (S[0][1][0]) "#">        */ CHPEG_INST(CHPEG_OP_GOTO, 308),
    /*   297 <-----:Repeat 137 (S[0][1][1]) []>       */ CHPEG_INST(CHPEG_OP_RSBEG, 0),
    /*   298 <-------:Predicate 139 (S[0][1][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PRED, 0),
    /*   299 <--------:CharClass  (S[0][1][1][0][0][0]) []> */ CHPEG_INST(CHPEG_OP_CHRCLS, 24),
    /*   300 <--------:CharClass  (S[0][1][1][0][0][0]) []> */ CHPEG_INST(CHPEG_OP_GOTO, 301),
    /*   301 <-------:Predicate 139 (S[0][1][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PMATCHF, 304),
    /*   302 <-------:Predicate 139 (S[0][1][1][0][0]) []> */ CHPEG_INST(CHPEG_OP_PNOMATS, 304),
    /*   303 <-------:Dot 140 (S[0][1][1][0][1]) "."> */ CHPEG_INST(CHPEG_OP_DOT, 304),
    /*   304 <-----:Repeat 137 (S[0][1][1]) []>       */ CHPEG_INST(CHPEG_OP_RSMAT, 297),
    /*   305 <-----:Repeat 137 (S[0][1][1]) []>       */ CHPEG_INST(CHPEG_OP_RSDONE, 0),
    /*   306 <-----:CharClass  (S[0][1][2]) []>       */ CHPEG_INST(CHPEG_OP_CHRCLS, 24),
    /*   307 <-----:CharClass  (S[0][1][2]) []>       */ CHPEG_INST(CHPEG_OP_GOTO, 308),
    /*   308 <---:Choice 134 (S[0]) []>               */ CHPEG_INST(CHPEG_OP_CISUCC, 310),
    /*   309 <---:Choice 134 (S[0]) []>               */ CHPEG_INST(CHPEG_OP_CIFAIL, 0),
    /*   310 <---:Choice 134 (S[0]) []>               */ CHPEG_INST(CHPEG_OP_CFAIL, 311),
    /*   311 <--:Repeat 133 (S) []>                   */ CHPEG_INST(CHPEG_OP_RSMAT, 286),
    /*   312 <--:Repeat 133 (S) []>                   */ CHPEG_INST(CHPEG_OP_RSDONE, 0),
    /*   313 <-:Definition 131 (def:S) []> {I}        */ CHPEG_INST(CHPEG_OP_ISUCC, 19),
    /*   314 <-:Definition 131 (def:S) []> {I}        */ CHPEG_INST(CHPEG_OP_IFAIL, 0)
    },

    .num_strings = 25,

    .strings = (unsigned char**)(char*[25]) {"{", "}", "<-", "/", "{<", "(", ")", "ILS", "a-zA-Z_", "a-zA-Z_0-9", "'", "\"", "[", "]", "-", "\\", "nrt'\"[]\\", "0-3", "0-7", "&!", "*+?", ".", " \t\r\n", "#", "\r\n"},

    .str_len = (int[25]) {1, 1, 2, 1, 2, 1, 1, 3, 7, 10, 1, 1, 1, 1, 1, 1, 8, 3, 3, 2, 3, 1, 4, 1, 2},
};
